site_name: ABCI Users Guide
site_description: AI Bridging Cloud Infrastructure (ABCI)
site_author: AIST
site_url: https://portal.abci.ai/docs/en/
repo_url: https://github.com/aistairc/abci-user-manual
edit_uri: edit/master/en/docs/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology (AIST)'
google_analytics: ['UA-118371652-2', 'portal.abci.ai']
nav:
  - 'Introduction': 'index.md'
  - Users Guide:
    - '1. ABCI System Overview': '01.md'
    - '2. ABCI System User Environment': '02.md'
    - '3. Job Execution Environment': '03.md'
    - '4. Storage': '04.md'
    - '5. Use Environment Modules': '05.md'
    - '6. Use Python': '06.md'
    - '7. Use GPU': '07.md'
    - '8. Use MPI': '08.md'
    - '9. Linux Container': '09.md'
    - '10. Software Development Environment': '10.md'
    - '11. Application Framework': '11.md'
    - '12. Remote desktop': '12.md'
    - '13. AWS': '13.md'
    - 'Appendix 1. Configuration of Installed Software': 'appendix1.md'
    - 'Appendix 2. Use of ABCI System for HPCI ': 'appendix2.md'
  - 'Known Issues': 'known-issues.md'
  - 'System Updates': 'system-updates.md'
  - 'Privacy Policy': 'https://portal.abci.ai/docs/privacy-policy/'
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'red'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite:
