site_name: ABCI 2.0 User Guide
site_description: ABCI 2.0 User Guide, English version
site_author: AIST
site_url: https://docs.abci.ai/en/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/en/docs/
copyright: 'Copyright &copy; 2021 National Institute of Advanced Industrial Science and Technology (AIST)'
nav:
  - 'Introduction': 'index.md'
  - 'ABCI System Overview': 'system-overview.md'
  - 'Getting Started ABCI': 'getting-started.md'
  - 'Job Execution': 'job-execution.md'
  - 'Storage': 'storage.md'
  - 'Environment Modules': 'environment-modules.md'
  - 'Python': 'python.md'
  - 'GPU': 'gpu.md'
  - 'MPI': 'mpi.md'
  - 'Containers': 'containers.md'
  - 'Development Tools': 'development-tools.md'
  - 'Appendix':
    - 'Appendix. Configuration of Installed Software': 'appendix/installed-software.md'
    - 'Appendix. Using ABCI with HPCI': 'appendix/using-abci-with-hpci.md'
    - 'Appendix. Communications with External Networks': 'appendix/external-networks.md'
    - 'Appendix. SSH Access to Compute Nodes': 'appendix/ssh-access.md'
  - 'Applications':
    - 'Overview': 'apps/index.md'
    - 'TensorFlow': 'apps/tensorflow.md'
    - 'PyTorch': 'apps/pytorch.md'
    - 'MXNet': 'apps/mxnet.md'
    - 'NVIDIA cuQuantom': 'apps/cuquantum.md'
  - 'Tips':
    - 'NVIDIA NGC': 'tips/ngc.md'
    - 'SHARP': 'tips/sharp.md'
    - 'Remote Desktop': 'tips/remote-desktop.md'
    - 'AWS CLI': 'tips/awscli.md'
    - 'PuTTY': 'tips/putty.md'
    - 'Jupyter Notebook': 'tips/jupyter-notebook.md'
    - 'Singularity Global Client': 'tips/sregistry-cli.md'
    - 'Spack': 'tips/spack.md'
    - 'Datasets': 'tips/datasets.md'
    - 'Amazon ECR': 'tips/dl-amazon-ecr.md'
    - 'Modules removed and alternatives': 'tips/modules-removed-and-alternatives.md'
  - 'ABCI Cloud Storage':
    - 'Overview': 'abci-cloudstorage.md'
    - 'Accounts and Access keys': 'abci-cloudstorage/cs-account.md'
    - 'Usage': 'abci-cloudstorage/usage.md'
    - 'Data Encryption': 'abci-cloudstorage/encryption.md'
    - 'Access Control (1) ': 'abci-cloudstorage/acl.md'
    - 'Access Control (2) ': 'abci-cloudstorage/policy.md'
    - 'Access Control (3) ': 'abci-cloudstorage/default-sub-group.md'
    - 'Publishing Datasets': 'abci-cloudstorage/publishing-datasets.md'
    - 'Caution': 'abci-cloudstorage/caution.md'
    - 'Using s3fs-fuse': 'abci-cloudstorage/s3fs-usage.md'
  - 'ABCI Datasets': 'abci-datasets.md'
  - 'ABCI Singularity Endpoint': 'abci-singularity-endpoint.md'
  - 'FAQ': 'faq.md'
  - 'Known Issues': 'known-issues.md'
  - 'System Updates': 'system-updates.md'
  - 'Operation Status': 'https://abci.ai/en/about_abci/info.html'
  - 'Contact': 'contact.md'
  - 'Links':
    - 'ABCI Web page': 'https://abci.ai/'
    - 'ABCI User Portal Guide': 'https://docs.abci.ai/portal/en/'
    - 'ABCI User Portal (Registration)': 'https://portal.abci.ai/user/project_register_app.php?lang=en'
    - 'ABCI User Portal (Login)':  'https://portal.abci.ai/user/login.php?lang=en'
extra:
  alternate:
    - name: 'English'
      link: 'https://docs.abci.ai/en/'
    - name: '日本語'
      link: 'https://docs.abci.ai/ja/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  language: 'en'
  palette:
    primary: 'red'
  features:
    - toc.integrate
  custom_dir: overrides
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
plugins:
  - search:
      lang: en
  - redirects:
      redirect_maps:
        '01.md': 'system-overview.md'
        '02.md': 'getting-started.md'
        '03.md': 'job-execution.md'
        '04.md': 'storage.md'
        '05.md': 'environment-modules.md'
        '06.md': 'python.md'
        '07.md': 'gpu.md'
        '08.md': 'mpi.md'
        '09.md': 'containers.md'
        '10.md': 'development-tools.md'
        '11.md': 'apps/index.md'
        '12.md': 'tips/remote-desktop.md'
        '13.md': 'tips/awscli.md'
        'appendix1.md': 'appendix/installed-software.md'
        'appendix2.md': 'appendix/using-abci-with-hpci.md'
        'ngc.md': 'tips/ngc.md'
