site_name: ABCI 3.0 User Guide
site_description: ABCI 3.0 User Guide
site_author: AIST
site_url: https://docs.abci.ai/v3/ja
copyright: 'Copyright &copy; 2024 National Institute of Advanced Industrial Science and Technology (AIST) / AIST Solutions Co. (AISol)'
nav:
  - 'はじめに': 'index.md'
  - 'ABCIシステムの概要': 'system-overview.md'
  - 'ABCIの利用開始': 'getting-started.md'
  - 'ジョブ実行': 'job-execution.md'
  - 'お問い合わせ': 'contact.md'
extra:
  alternate:
    - name: 'English'
      link: 'https://docs.abci.ai/v3/en/'
    - name: '日本語'
      link: 'https://docs.abci.ai/v3/ja/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  palette:
    primary: 'red'
  features:
    - toc.integrate
  custom_dir: overrides
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
plugins:
  - search:
      lang: ja