site_name: ABCI 3.0 Portal Guide
site_description: ABCI 3.0 Portal Guide, Japanese version
site_author: AIST
site_url: https://docs.abci.ai/portal/ja/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/portal/ja/docs/
copyright: 'Copyright &copy; 2021 National Institute of Advanced Industrial Science and Technology (AIST)'
nav:
  - 'はじめに': 'index.md'
  - '1. 利用グループ新規申請': '01.md'
  - '2. 利用者ポータル': '02.md'
  - '3. 利用管理者権限': '03.md'
  - '4. 利用グループ継続申請': '04.md'
  - 'リンク':
    - 'ABCI Webページ': 'https://abci.ai/ja/'
    - 'ABCI 3.0利用者手引き': 'https://docs.abci.ai/v3/ja/'
    - 'ABCI利用者ポータル (利用申請)': 'https://portal.v3.abci.ai/ProjectApplication_01'
    - 'ABCI利用者ポータル (ログイン)':  'https://portal.v3.abci.ai/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  language: 'ja'
  palette:
    primary: 'blue'
  features:
    - toc.integrate
  custom_dir: overrides
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
plugins:
  - search:
      lang: ja
