site_name: ABCI Users Guide
site_description: AI Bridging Cloud Infrastructure (ABCI)
site_author: AIST
site_url: https://portal.abci.ai/docs/ja/
repo_url: https://github.com/aistairc/abci-user-manual
edit_uri: edit/master/ja/docs/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology (AIST)'
google_analytics: ['UA-118371652-2', 'portal.abci.ai']
nav:
  - 'はじめに': 'index.md'
  - '利用手引き':
    - '1. ABCIシステムの概要': '01.md'
    - '2. ABCIシステム利用環境': '02.md'
    - '3. ジョブ実行環境': '03.md'
    - '4. ストレージ': '04.md'
    - '5. Environment Modulesの利用': '05.md'
    - '6. Pythonの利用': '06.md'
    - '7. GPUの利用': '07.md'
    - '8. MPIの利用': '08.md'
    - '9. Linuxコンテナ': '09.md'
    - '10. プログラム開発環境': '10.md'
    - '11. ABCIでのリモートデスクトップ利用': '11.md'
    - '12. AWS の利用': '12.md'
    - '付録1. インストール済みソフトウェアの構成': 'appendix1.md'
    - '付録2. HPCIによるABCIシステム利用': 'appendix2.md'
  - '各種ライブラリ':
    - 'TensorFlow': 'apps/tensorflow.md'
    - 'Chainer': 'apps/chainer.md'
    - 'その他': 'apps/other.md'
  - 'システム更新履歴': 'system-updates.md'
  - 'プライバシーポリシー': 'https://portal.abci.ai/docs/privacy-policy/'
theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'red'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite:
