site_name: ABCI Users Guide
site_description: ABCI Users Guide, Japanese version
site_author: AIST
site_url: https://docs.abci.ai/ja/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/ja/docs/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology (AIST)'
google_analytics:
  - 'UA-118371652-2'
  - 'auto'
nav:
  - 'はじめに': 'index.md'
  - '利用手引き':
    - '1. ABCIシステムの概要': '01.md'
    - '2. ABCIシステム利用環境': '02.md'
    - '3. ジョブ実行環境': '03.md'
    - '4. ストレージ': '04.md'
    - '5. Environment Modulesの利用': '05.md'
    - '6. Pythonの利用': '06.md'
    - '7. GPUの利用': '07.md'
    - '8. MPIの利用': '08.md'
    - '9. Linuxコンテナ': '09.md'
    - '10. プログラム開発環境': '10.md'
    - '付録. インストール済みソフトウェアの構成': 'appendix/installed-software.md'
    - '付録. HPCIによるABCIシステム利用': 'appendix/using-abci-with-hpci.md'
    - '付録. 外部ネットワークとの通信': 'appendix/external-networks.md'
  - '各種アプリケーション':
    - '概要': 'apps/index.md'
    - 'TensorFlow': 'apps/tensorflow.md'
    - 'TensorFlow Keras': 'apps/tensorflow-keras.md'
    - 'PyTorch': 'apps/pytorch.md'
    - 'MXNet': 'apps/mxnet.md'
    - 'Chainer': 'apps/chainer.md'
    - 'その他': 'apps/others.md'
  - 'Tips':
    - 'リモートデスクトップの利用': 'tips/remote-desktop.md'
    - 'AWS CLIの利用': 'tips/awscli.md'
    - 'Tera Termの利用': 'tips/tera-term.md'
    - 'PuTTYの利用': 'tips/putty.md'
    - 'Jupyter Notebookの利用': 'tips/jupyter-notebook.md'
    - 'Singularity Global Clientの利用': 'tips/sregistry-cli.md'
    - 'Spackによるソフトウェア管理': 'tips/spack.md'
    - 'データセットの利用': 'tips/datasets.md'
    - 'Amazon ECR からコンテナ取得': 'tips/dl-amazon-ecr.md'
  - 'NVIDIA NGC': 'ngc.md'
  - 'ABCI クラウドストレージ':
    - '概要': 'abci-cloudstorage.md'
    - 'アカウントとアクセスキー': 'abci-cloudstorage/cs-account.md'
    - '使い方': 'abci-cloudstorage/usage.md'
    - 'データの暗号化': 'abci-cloudstorage/encryption.md'
    - 'アクセス制御（1）': 'abci-cloudstorage/acl.md'
    - 'アクセス制御（2）': 'abci-cloudstorage/policy.md'
  - 'ABCI Singularity エンドポイント': 'abci-singularity-endpoint.md'
  - 'FAQ': 'faq.md'
  - '既知の問題': 'known-issues.md'
  - 'システム更新履歴': 'system-updates.md'
  - '運転状況': 'https://abci.ai/ja/about_abci/info.html'
  - 'お問い合わせ': 'contact.md'
  - 'リンク':
    - 'ABCI Webページ': 'https://abci.ai/ja/'
    - 'ABCI利用ポータル手引き': 'https://docs.abci.ai/portal/ja/'
    - 'ABCI利用ポータル(利用申請)': 'https://portal.abci.ai/user/project_register_app.php?lang=ja'
    - 'ABCI利用ポータル(ログイン)':  'https://portal.abci.ai/user/login.php?lang=ja'
  - 'English version': 'https://docs.abci.ai/en/'
theme:
  name: 'material'
  logo:
    icon: 'cloud'
  language: 'ja'
  palette:
    primary: 'red'
    accent: 'red'
  feature:
    tabs: false
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
