site_name: ABCI Users Guide
site_description: ABCI Users Guide, Japanese version
site_author: AIST
site_url: https://docs.abci.ai/ja/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/ja/docs/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology (AIST)'
google_analytics:
  - 'UA-118371652-2'
  - 'auto'
nav:
  - 'はじめに': 'index.md'
  - '利用手引き':
    - '1. ABCIシステムの概要': '01.md'
    - '2. ABCIシステム利用環境': '02.md'
    - '3. ジョブ実行環境': '03.md'
    - '4. ストレージ': '04.md'
    - '5. Environment Modulesの利用': '05.md'
    - '6. Pythonの利用': '06.md'
    - '7. GPUの利用': '07.md'
    - '8. MPIの利用': '08.md'
    - '9. Linuxコンテナ': '09.md'
    - '10. プログラム開発環境': '10.md'
    - '付録1. インストール済みソフトウェアの構成': 'appendix1.md'
    - '付録2. HPCIによるABCIシステム利用': 'appendix2.md'
  - '各種アプリケーション':
    - '概要': 'apps/index.md'
    - 'TensorFlow': 'apps/tensorflow.md'
    - 'Chainer': 'apps/chainer.md'
    - 'その他': 'apps/others.md'
  - 'Tips':
    - 'リモートデスクトップの利用': 'tips/remote-desktop.md'
    - 'AWS CLIの利用': 'tips/awscli.md'
    - 'GCC 7.3.0の利用': 'tips/gcc-7.3.0.md'
    - 'Tera Termの利用': 'tips/tera-term.md'
    - 'PuTTYの利用': 'tips/putty.md'
  - 'NVIDIA GPU Cloud (NGC)': 'ngc.md'
  - 'ABCI クラウドストレージ':
    - '概要': 'abci-cloudstorage.md'
    - '使い方': 'abci-cloudstorage/usage.md'
    - '利用管理者用アカウント': 'abci-cloudstorage/management.md'
    - 'ポリシー設定': 'abci-cloudstorage/policy.md'
  - '既知の問題': 'known-issues.md'
  - 'システム更新履歴': 'system-updates.md'
  - '運転状況': 'https://abci.ai/ja/about_abci/info.html'
  - 'リンク':
    - 'ABCI Webページ': 'https://abci.ai/ja/'
    - 'ABCI利用ポータル手引き': 'https://docs.abci.ai/portal/ja/'
    - 'ABCI利用ポータル(利用申請)': 'https://portal.abci.ai/user/project_register_app.php?lang=ja'
    - 'ABCI利用ポータル(ログイン)':  'https://portal.abci.ai/user/login.php?lang=ja'
  - 'English version': 'https://docs.abci.ai/en/'
theme:
  name: 'material'
  logo:
    icon: 'cloud'
  language: 'ja'
  palette:
    primary: 'red'
    accent: 'red'
  feature:
    tabs: false
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
