site_name: ABCI 3.0 User Guide
site_description: ABCI 3.0 User Guide, English version
site_author: AIST
site_url: https://docs.abci.ai/v3/en
copyright: 'Copyright &copy; 2024 National Institute of Advanced Industrial Science and Technology (AIST) / AIST Solutions Co. (AISol)'
nav:
  - 'Introduction': 'index.md'
  - 'ABCI System Overview': 'system-overview.md'
  - 'Getting Started ABCI': 'getting-started.md'
  - 'Job Execution': 'job-execution.md'
  - 'Environment Modules': 'environment-modules.md'
  - 'Python': 'python.md'
  - 'MPI': 'mpi.md'
  - 'Containers': 'containers.md'
  - 'Development Tools': 'development-tools.md'
  - 'Tips':
    - 'GPUDirect Storage': 'tips/gds.md'
    - 'PuTTY': 'tips/putty.md'
    - 'How to add a Python virtual environment to JupyterLab': 'tips/jupyterlab_venv.md'
  - 'ABCI Cloud Storage':
    - 'Overview': 'abci-cloudstorage.md'
    - 'Cloud Storage Account DIrectories and Access keys': 'abci-cloudstorage/cs-account.md'
    - 'Usage': 'abci-cloudstorage/usage.md'
    - 'Data Encryption': 'abci-cloudstorage/encryption.md'
    - 'Access Control (1) ': 'abci-cloudstorage/acl.md'
    - 'Access Control (2) ': 'abci-cloudstorage/policy.md'
    - 'Caution': 'abci-cloudstorage/caution.md'
    - 'Using s3fs-fuse': 'abci-cloudstorage/s3fs-usage.md'
  - 'Open OnDemand':
    - 'Using Open OnDemand': 'open-ondemand/index.md'
    - 'Ineractive Apps': 'open-ondemand/interactive-apps.md'
  - 'Known Issues': 'known-issues.md'
  - 'System Updates': 'system-updates.md'
  - 'Contact': 'contact.md'
  - 'Various Requests':
    - 'Request for Communication with External Networks': 'requests/external-networks.md'
    - 'Request for Increasing Group Area Quota': 'requests/group-area-quota-increase.md'
extra:
  alternate:
    - name: 'English'
      link: 'https://docs.abci.ai/v3/en/'
    - name: '日本語'
      link: 'https://docs.abci.ai/v3/ja/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  palette:
    primary: 'red'
  features:
    - toc.integrate
  custom_dir: overrides
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
plugins:
  - search:
      lang: en
